server:
  http_port: :8080

# docker run --name mysql-im -e MYSQL_ROOT_PASSWORD=Kirito768168 -p 3307:3306 -d mysql:latest
mysql:
  host: mysql-im
  port: 3306
  username: root
  password: Kirito768168
  database: im_db

# Redis 配置
redis:
  addr: "redis:6379"  # Redis 服务器地址
  password: ""             # Redis 密码，如果没有可以留空
  db: 0                    # Redis 数据库索引

# docker run --name mongo-im -p 27017:27017 -d mongo:latest
#mongodb:
#  uri: mongodb://localhost:27017
#  database: im_system

jwt_secret: Kirito768168